---
persistence:
  redis:
    host: 127.0.0.1  # The IP address or the hostname to your Redis server, 127.0.0.1 if same as BBGO  
    port: 6379  # Port to Redis server, default 6379
    db: 0  # DB number to use. You can set to another DB to avoid conflict if other applications are using Redis too.

sessions:
  okex:
    exchange: okex
    envVarPrefix: okex
    margin: true
    isolatedMargin: false
    isolatedMarginSymbol: OPUSDT

exchangeStrategies:
- on: okex
  jarvis:
    llm:
      openai:
        enabled: true
        model: "gpt-3.5-turbo-0301"
    env:
      exchange:
        window_size: 20
      include_events:
        - kline_changed
        - rsi_changed
        - boll_changed
        - fng_changed
        - position_changed
        - update_finish
    notify:
      feishu:
        enabled: false
        tenant_key: "2cc4e3dc7f8e175d"
        receive_id_type: "chat_id"
        receive_id: "oc_30913e3222c7beca3efd4d9cc2d832af"
      feishu_hook:
        enabled: true
        url: "https://open.feishu.cn/open-apis/bot/v2/hook/e926c8b5-50e6-41e8-8f70-12a8631dfd93"
    chat:
      feishu:
        enabled: false
        server_port: 3000
    symbol: OPUSDT
    interval: 5m
    leverage: 3
    max_window_size: 20
    strategy: "Trading on the right side, trailing stop loss 3%, trailing stop profit 10%."